# app/services/presets.py
# Preset derivati da Rules.xlsx — versione RANGE (min/max)
PRESETS = {
    "Warm-up Daytime": dict(
        tempo_min=70, tempo_max=90,
        energy_min=0.45, energy_max=0.65,
        danceability_min=0.35, danceability_max=0.55,
        valence_min=0.65, valence_max=0.85,
        acousticness_min=0.60, acousticness_max=0.80,
        instrumentalness_min=0.45, instrumentalness_max=0.65,
        speechiness_min=0.00, speechiness_max=0.15,  # "tetto" -> floor 0 = no floor
        liveness_min=0.00, liveness_max=0.25,
        loudness_min=-16.0, loudness_max=-10.0,
        explicit_allowed=False,
        genre="",
    ),

    "Lunch Orders (Variety)": dict(
        tempo_min=90, tempo_max=110,
        energy_min=0.70, energy_max=0.90,
        danceability_min=0.60, danceability_max=0.80,
        valence_min=0.70, valence_max=0.90,
        acousticness_min=0.65, acousticness_max=0.85,
        instrumentalness_min=0.35, instrumentalness_max=0.55,
        speechiness_min=0.00, speechiness_max=0.30,
        liveness_min=0.00, liveness_max=0.30,
        loudness_min=-12.0, loudness_max=-6.0,
        explicit_allowed=False,
        genre="",
    ),

    "Lunch Consumption (Slow Down)": dict(
        tempo_min=60, tempo_max=80,
        energy_min=0.35, energy_max=0.55,
        danceability_min=0.25, danceability_max=0.45,
        valence_min=0.55, valence_max=0.75,
        acousticness_min=0.45, acousticness_max=0.65,
        instrumentalness_min=0.50, instrumentalness_max=0.70,
        speechiness_min=0.00, speechiness_max=0.15,
        liveness_min=0.00, liveness_max=0.25,
        loudness_min=-16.0, loudness_max=-10.0,
        explicit_allowed=False,
        genre="",
    ),

    "Afternoon Walk-in (Upsell)": dict(
        tempo_min=70, tempo_max=90,
        energy_min=0.45, energy_max=0.65,
        danceability_min=0.35, danceability_max=0.55,
        valence_min=0.65, valence_max=0.85,
        acousticness_min=0.40, acousticness_max=0.60,
        instrumentalness_min=0.40, instrumentalness_max=0.60,
        speechiness_min=0.00, speechiness_max=0.15,
        liveness_min=0.00, liveness_max=0.30,
        loudness_min=-16.0, loudness_max=-10.0,
        explicit_allowed=False,
        genre="",
    ),

    "Aperitivo (High Spend Push)": dict(
        tempo_min=90, tempo_max=110,
        energy_min=0.70, energy_max=0.85,
        danceability_min=0.55, danceability_max=0.70,
        valence_min=0.75, valence_max=0.90,
        acousticness_min=0.35, acousticness_max=0.55,
        instrumentalness_min=0.15, instrumentalness_max=0.35,
        speechiness_min=0.00, speechiness_max=0.20,
        liveness_min=0.00, liveness_max=0.35,
        loudness_min=-14.0, loudness_max=-8.0,
        explicit_allowed=False,
        genre="",
    ),

    "Dinner Orders (Efficiency)": dict(
        tempo_min=105, tempo_max=125,
        energy_min=0.70, energy_max=0.85,
        danceability_min=0.55, danceability_max=0.70,
        valence_min=0.65, valence_max=0.80,
        acousticness_min=0.15, acousticness_max=0.35,
        instrumentalness_min=0.10, instrumentalness_max=0.30,
        speechiness_min=0.00, speechiness_max=0.20,
        liveness_min=0.00, liveness_max=0.35,
        loudness_min=-12.0, loudness_max=-6.0,
        explicit_allowed=False,
        genre="",
    ),

    "Dinner Consumption (Stability)": dict(
        tempo_min=80, tempo_max=100,
        energy_min=0.45, energy_max=0.60,
        danceability_min=0.35, danceability_max=0.55,
        valence_min=0.55, valence_max=0.75,
        acousticness_min=0.40, acousticness_max=0.60,
        instrumentalness_min=0.45, instrumentalness_max=0.65,
        speechiness_min=0.00, speechiness_max=0.15,
        liveness_min=0.00, liveness_max=0.30,
        loudness_min=-14.0, loudness_max=-8.0,
        explicit_allowed=False,
        genre="",
    ),

    "Closing / Soft Exit": dict(
        tempo_min=55, tempo_max=75,
        energy_min=0.20, energy_max=0.35,
        danceability_min=0.15, danceability_max=0.30,
        valence_min=0.45, valence_max=0.65,
        acousticness_min=0.60, acousticness_max=0.80,
        instrumentalness_min=0.60, instrumentalness_max=0.85,
        speechiness_min=0.00, speechiness_max=0.10,
        liveness_min=0.00, liveness_max=0.20,
        loudness_min=-18.0, loudness_max=-12.0,
        explicit_allowed=False,
        genre="ambient",
    ),
}
